@startuml

package "Pg" {
    [Etc]
    [Data]
    [Rule]
    [Puzzle]
    [Scene.Game]
    [SceneData]
    [App]
    Data ---> Etc
    Rule ---> Etc
    Rule ---> Data
    Puzzle ---> Etc
    Puzzle ---> Data
    Puzzle ---> Rule
    SceneData ---> Data
    SceneData ---> Etc
    Scene.Game ---> Etc
    Scene.Game ---> Data
    Scene.Game ---> Puzzle
    Scene.Game ---> App
    Scene.Game ---> SceneData
    App ---> Etc
    App ---> SceneData
}

@enduml
